# Generated by Django 5.0.7 on 2024-09-14 14:45

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='profile_pic',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='accounts/images/default/default_pfp.png', force_format=None, keep_meta=True, quality=-1, scale=None, size=[50, 50], upload_to='accounts/images/'),
        ),
    ]
