# Generated by Django 5.0.7 on 2024-09-21 18:53

import django.db.models.deletion
import django_resized.forms
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_accountuser_bio_alter_accountuser_profile_pic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('profile_pic', django_resized.forms.ResizedImageField(blank=True, crop=None, default='accounts/images/default/default_pfp.png', force_format=None, keep_meta=True, quality=-1, scale=None, size=[50, 50], upload_to='accounts/images/')),
                ('friends', models.ManyToManyField(blank=True, to='accounts.profile')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='AccountUser',
        ),
    ]
